# Placeholder for Shopify CLI to function properly.

name=StorefrontX: App builder

scopes = "read_products","write_products","read_customers","write_customers","offline_access","read_cart_transforms"